# Generated by Django 3.1.5 on 2021-01-07 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='profilesimages')),
                ('address', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('for_who', models.CharField(choices=[('Myself', 'Myself'), ('Nonprofit', 'Nonprofit')], max_length=200)),
                ('zip_code', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media-petition')),
                ('story', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube', embed_video.fields.EmbedVideoField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
