# Generated by Django 3.1.5 on 2021-01-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210109_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='donated',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
