# Generated by Django 3.1.5 on 2021-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210110_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='donated',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
