# Generated by Django 3.1.5 on 2021-01-12 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210110_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
